package org.netcracker.constants;

public enum TukCnctOrderStatus {
    LOCK_SOLD,ORDER_PICK_RECEIVED,ORDER_AWAITING_PICKING, ORDER_AWAITING_UNPICKING,
    ORDER_AWAITING_COLLECTION,ORDER_COLLECTED,ORDER_CANCELLED_AWAITING_UNPICKING,

    ORDER_CANCELLED_NOT_PICKED_CVOS,ORDER_CANCELLED_NOT_PICKED_IBM, ORDER_RETURNED_NOT_COLLECTED,
    LOCK_FAILED, PICK_FAILED_USER_ACTIONED, COLLECTION_EXTENDED, ORDER_COLLECTED_CUSTOMER_NOT_PRESENT,UNKNOWN
}
